### PR TITLE
Fix signing by identity (ECDSA)

### PR DESCRIPTION
**Pull request by quevedo**
- When signing by identity, if no certificate is available for the default key and its type does not corresponds to the DEFAULT_KEY_PARAMS a new pair of DEFAULT_KEY_PARAMS keys is created, set as default and used for signing. Solved by checking the type of key of the default key pair for the identity.

- Unit tests addressing the issue are also included.

- Added a default value (false) to 'isKsk' for 'KeyChain::generateEcdsaKeyPairAsDefault'

### CODE REVIEW

**Comment by cawka** [comment]
Thanks!

I have updated your commits a little and pushed them for the code review and continuous integration testing:
- http://gerrit.named-data.net/#/c/2692/
- http://gerrit.named-data.net/#/c/2693

Please feel free to comment on the changes I made / address comments from other reviewers (if any).

**Comment by cawka** [comment]
José, can you please give additional comments in redmine issues I just created (http://redmine.named-data.net/issues/3438 and http://redmine.named-data.net/issues/3439)

**Comment by quevedo** [comment]
Thanks for the great descriptions of the issue, nothing to add there. I will keep track of the comments and provide further clarifications if required.

**Comment by Pesa** [comment]
This PR should be closed.

**Pull request closed without merging**
