### PR TITLE
Bugs in function detail::getEvpPkeyType() in the origianl verion of ndn-cxx.

### PR DESCRIPTION
**Pull request by liupenghui-owen**
The origianl verion of ndn-cxx tests the key type through PrivateKey.getKeyType()->detail::getEvpPkeyType(), which 
has a bug when testing the ECC key type, it cannot distinguish the different curve types under the same ECC system, such as ECDSA and SM2. The public and private key formats between ECDSA and SM2 are the same, but with the only difference is the algorithm operations and curve selection, i.e. the EC group is different. Specifically, 

① when the SM2 safebag imported from outside(such as from other machines) through the standard command 'ndnsec import', the SM2 type through detail::getEvpPkeyType() cannot be obtained, That is, SM2 and ECDSA types cannot be distinguished. At the same time, PublicKey.getKeyType()->detail::getEvpPkeyType() cannot obtain the SM2 type of public key, that is, SM2 and ECDSA cannot be distinguished. The core cause of the problem is that there is not enough key type information expression when exporting safebag of the key and certificate, and there is not enough EC group information when importing safebag into the internal format expression of OpenSSL (via d2i_AutoPrivateKey、d2i_PUBKEY). Therefore, when obtaining the type through detail::getEvpPkeyType(), it is impossible to distinguish the SM2 and ECDSA key types under the same EC system.

② When SM2 key is generated locally, the SM2 type of the key can be obtained via detail::getEvpPkeyType().  This is because the initial EC group information is required when the key is generated locally. Therefore, we can call EVP_PKEY_id() in detail::getEvpPkeyType() to further distinguish SM2 and ECDSA key types.

In general, the bug is caused by that there is no enough group information when importing safebag outside in the current design directly via d2i_AutoPrivateKey()、d2i_PUBKEY(). And the private key file only stores a key, no other information. therefore, it cannot distinguish the different curve types under the same ECC system, such as ECDSA and SM2.

In order to ensure the compatibility and meet the requirements of manually importing and exporting key safebag,
we have modified the internal interfaces, stored the type of key imported or generated from safebag in the SQLite3 db in Pib 
(the key type is interpreted and obtained from the sig type of certificate in safebag), and added a key type parameter when calling the internal interfaces. The external interface remains unchanged.

In addition, the original version of ndn-cxx does not support the generation of HMAC key and does not support the use of HMAC signature algorithm through the general signature interface. There is a bug in toPkcs1(), which does not distinguish 
the key processing of asymmetric algorithms such as ECDSA and HMAC algorithm. see the function toPkcs1(). 
This new version of ndn-cxx also provides a HMAC key file, which can be generated and updated at any time by commanding 'ndnsec key-gen', Keyname:/localhost/identity/hmac/KEY/123456789, stored in the directory $("HOME")/.ndn/ndnsec-key-file/, 
the file name is 8436ea04965f58d93b751d551f5634646e2ff17fcd720bd413e51106c682808f.privkey. 

In addition, the HMAC function can be called through the general signature interface. The user app only needs to define the parameters.

### CODE REVIEW

**Comment by Pesa** [comment]
> The origianl verion of ndn-cxx tests the key type through PrivateKey.getKeyType()->detail::getEvpPkeyType(), which has a bug when testing the ECC key type, it cannot distinguish the different curve types under the same ECC system, such as ECDSA and SM2. 

Well, ndn-cxx does not support SM2, so I wouldn't call this a bug, it's more like a feature request.

> ① when the SM2 safebag imported from outside(such as from other machines) through the standard command 'ndnsec import', the SM2 type through detail::getEvpPkeyType() cannot be obtained, That is, SM2 and ECDSA types cannot be distinguished.

As I said above, ndn-cxx doesn't support SM2 so you're relying on a feature that simply isn't there currently.

> At the same time, PublicKey.getKeyType()->detail::getEvpPkeyType() cannot obtain the SM2 type of public key, that is, SM2 and ECDSA cannot be distinguished. The core cause of the problem is that there is not enough key type information expression when exporting safebag of the key and certificate, and there is not enough EC group information when importing safebag into the internal format expression of OpenSSL (via d2i_AutoPrivateKey、d2i_PUBKEY). Therefore, when obtaining the type through detail::getEvpPkeyType(), it is impossible to distinguish the SM2 and ECDSA key types under the same EC system.

`SafeBag` uses the `EncryptedPrivateKeyInfo` from PKCS8 for the private key, are you saying that `EncryptedPrivateKeyInfo` cannot distinguish between ECDSA and SM2? Or that openssl cannot distinguish? If so, this sounds like a bigger problem than just ndn-cxx. If that's not the problem, then I'm not sure I follow.

> In addition, the original version of ndn-cxx does not support the generation of HMAC key

Are you sure? IIRC generation of HMAC keys should work find both via `security::transform::generatePrivateKey()` and also through the higher-level `Tpm` and `KeyChain` interfaces. If that's not the case, please elaborate... what error are you getting?

> and does not support the use of HMAC signature algorithm through the general signature interface.

I believe this should also be supported already, using `SigningInfo::SIGNER_TYPE_HMAC`. But please explain if there are any lingering issues. I don't think HMAC has been used much in ndn-cxx and validation-side support is missing.

> There is a bug in toPkcs1(), which does not distinguish the key processing of asymmetric algorithms such as ECDSA and HMAC algorithm. see the function toPkcs1().

HMAC is not an asymmetric algorithm so I'm not following what you're saying.

**Comment by Pesa** [comment]
Also please note that the commits in this PR are unreadable. It seems that the first commit is deleting every single file and the second commit adds everything back (I assume with your changes?), so it's impossible to see what's actually happening. Even the combined diff is unreadable because it was based on a much older version of ndn-cxx, so there are tons of unrelated changes.

**Comment by liupenghui1982** [comment]
> As I said above, ndn-cxx doesn't support SM2 so you're relying on a feature that simply isn't there currently.
> 
> >

Yes,  I deleted the original version  when I forked this new version. :)
Actually, this is a forked version from V0.7.1, and I will pull a new request from ndn-cxx release version 0.8.0 this day later.

**Comment by liupenghui1982** [comment]
> I believe this should also be supported already, using `SigningInfo::SIGNER_TYPE_HMAC`. But please explain if there are any lingering issues. I don't think HMAC has been used much in ndn-cxx and validation-side support is missing.

Yes, HMAC has not been used much, but I try to support it in our project.
Actually, HMAC is not  an asymmetric algorithm, signatue-side is the same as validation-side.

**Comment by liupenghui1982** [comment]
> I will pull a new request from ndn-cxx release version 0.8.0 this day later.

**Comment by liupenghui1982** [comment]
> Also please note that the commits in this PR are unreadable. It seems that the first commit is deleting every single file and the second commit adds everything back (I assume with your changes?), so it's impossible to see what's actually happening. Even the combined diff is unreadable because it was based on a much older version of ndn-cxx, so there are tons of unrelated changes.

Yes, I deleted the original version when I forked this new version. :)
Actually, this is a forked version from ndn-cxx release v0.7.1, and I will pull a new request from ndn-cxx release version 0.8.0 this day later.

**Comment by liupenghui1982** [comment]
> Are you sure? IIRC generation of HMAC keys should work fine both via `security::transform::generatePrivateKey()` and also through the higher-level `Tpm` and `KeyChain` interfaces when using an in-memory TPM. If that's not the case, please elaborate... what error are you getting?
> I  use sqlite3 TPM in our project, hope to generate the HMAC key file in $("HOME")/.ndn/ndnsec-key-file/ as other asymmetric algorithm.   :)
> >

**Comment by liupenghui1982** [comment]
> `SafeBag` uses the `EncryptedPrivateKeyInfo` from PKCS8 for the private key, are you saying that `EncryptedPrivateKeyInfo` cannot distinguish between ECDSA and SM2? Or that openssl cannot distinguish? If so, this sounds like a bigger problem than just ndn-cxx. If that's not the problem, then I'm not sure I follow.

Yes,  after imported from outside SafeBag, Openssl cannot distinguish between ECDSA and SM2 through detail::getEvpPkeyType(), it seems that there is not enough EC group information when importing SafeBag into the internal format expression of OpenSSL (via d2i_AutoPrivateKey()、d2i_PUBKEY()). 
This problem occurs when importing the SafeBag generated from other machines. In this case, detail::getEvpPkeyType() just return EC type, even we call EVP_PKEY_id() in detail::getEvpPkeyType() to further distinguish SM2 and ECDSA key types, it still return EC type.  it cannot distinguish the SM2 and ECDSA key types under the same EC system.  This bug is caused by that there is no enough group information.
But when SM2 key is generated locally, the SM2 type of the key can be obtained through detail::getEvpPkeyType(). This is because the initial EC group information is initiated and required when the SM2 key is generated locally, see security::transform::generatePrivateKey() in our SM2 integration in this version. In this case, we can call EVP_PKEY_id() in detail::getEvpPkeyType() to further distinguish SM2 and ECDSA key types. 
So I think this orignal version of ndn-cxx can be impoved to add a parameter KeyType in sqlite3 Pib db to solve this problem,  then detail::getEvpPkeyType() can get the Key type from sqlite3 Pib, and the true KeyType value can get from the import command or imported from the certificate sig-type value.

**Comment by liupenghui1982** [comment]
this ndn-cxx master branch  is forked from original release 0.8.0

**Comment by liupenghui1982** [comment]
> Also please note that the commits in this PR are unreadable. It seems that the first commit is deleting every single file and the second commit adds everything back (I assume with your changes?), so it's impossible to see what's actually happening. Even the combined diff is unreadable because it was based on a much older version of ndn-cxx, so there are tons of unrelated changes.


Just now, I updated a new version, this ndn-cxx master branch is forked from original release 0.8.0.

**Comment by liupenghui1982** [comment]
Dear Pesavento,


I have updated it based on ndn-cxx 0.8.0, please have a look when your necessary. Thanks!


Br,
Owen LIU.




At 2022-04-22 01:55:11, "Davide Pesavento" ***@***.***> wrote:

Also please note that the commits in this PR are unreadable. It seems that the first commit is deleting every single file and the second commit adds everything back (I assume with your changes?), so it's impossible to see what's actually happening. Even the combined diff is unreadable because it was based on a much older version of ndn-cxx, so there are tons of unrelated changes.

**Comment by Pesa** [comment]
We use gerrit for this project so we cannot accept pull requests on github. See [CONTRIBUTING](https://github.com/named-data/.github/blob/main/CONTRIBUTING.md).
Please submit your patch to https://gerrit.named-data.net/

**Pull request closed without merging**
